# Use official Node.js image
FROM node:18-alpine

# Install required system dependencies for Tesseract
RUN apk add --no-cache tesseract-ocr tesseract-ocr-data-eng

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --only=production


# Copy the rest of the app
COPY . .

# Expose Next.js port
EXPOSE 3000

# Build the Next.js app
RUN npm run build

# Run the command to start the development server
CMD ["npm", "run", "start"]